- .circleci/config.yml
- charts/litmus/.helmignore
- charts/litmus/Chart.yaml
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/crds/chaosexperiment_crd.yaml
- charts/litmus/crds/chaosresult_crd.yaml
- charts/litmus/templates/_helpers.tpl
- charts/litmus/templates/clusterrole.yaml
- charts/litmus/templates/clusterrolebinding.yaml
- charts/litmus/templates/deployment.yaml
- charts/litmus/templates/serviceaccount.yaml
- charts/litmus/values.yaml
- Adds helm charts for Litmus Chaos Operator and CRDs
- Fixes https://github.com/litmuschaos/litmus/issues/1221
> (feat)helm: add helm3 charts for litmus chaos operator and crds

- README.md
- Update readme with install instructions 
- Will be updating w/ upgrade steps in an upcoming PR
> (chore)doc: update readme with install steps

- charts/litmus/Chart.yaml
- charts/litmus/templates/NOTES.txt
- Adds more metadata into Chart.yaml (Ref: https://helm.sh/docs/topics/charts/) 
- Adds useful instructions into NOTES.txt
** PreRequisites to addition into helm hub
> (refactor)chart: add notes and chart descriptions

- charts/litmus/Chart.yaml
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/templates/deployment.yaml
- charts/litmus/values.yaml
> (chore)chart: update operator chart and crds for v1.3.0

- charts/litmus/Chart.yaml
> (fix)chart: remove icon as an array element

- charts/litmus/README.md
> Add README for helm-chart

- .circleci/config.yml
- .circleci/ct.yaml
- .circleci/lintconf.yaml
> Add chart testing

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/deployment.yaml
- charts/litmus/values.yaml
This pull request makes the following changes:
- operator and runner values are located under different objects like that:
```
operator:
image:
repository: litmuschaos/chaos-operator
tag: 1.3.0
pullPolicy: Always
runner:
image:
repository: litmuschaos/chaos-runner
tag: 1.3.0
```
- added pull request template
closes #13
> Change values model for images based on component

- README.md
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/crds/chaosexperiment_crd.yaml
- charts/litmus/crds/chaosresult_crd.yaml
- charts/litmus/templates/clusterrole.yaml
- charts/litmus/values.yaml
Signed-off-by: Rahul M Chheda <rahul.chheda@mayadata.io>
- fixes #
> Added latest CRD validations,and clusterrole

- .circleci/config.yml
- README.md
- fixes #20 
- Uses the "ignore" directive to ensure builds do not occur on gh-pages, while it occurs on all other. 
> (chore)ci: prevent builds on gh-pages branch

- README.md
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
- upgrading litmus helm chart to 1.5.0
- fixes #
> chore(chart): upgrading litmus helm chart to 1.5.0

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- Add contributing guide to clarify the process
- Add code of conduct
- Update readme with contributing guide
- Add license info to README
- Add badges
- fixes #26 
Badges preview:
> Add contributing guide & code of conduct, update readme with additional section

- README.md
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> feat(helm): Update chart with 1.6.0 version of litmus

- charts/kubernetes-chaos/.helmignore
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/crds/chaosexperiment_crd.yaml
- charts/kubernetes-chaos/templates/_helpers.tpl
- charts/kubernetes-chaos/templates/clusterrole.yaml
- charts/kubernetes-chaos/templates/clusterrolebinding.yaml
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/disk-fill.yaml
- charts/kubernetes-chaos/templates/disk-loss.yaml
- charts/kubernetes-chaos/templates/docker-service-kill.yaml
- charts/kubernetes-chaos/templates/kubelet-service-kill.yaml
- charts/kubernetes-chaos/templates/node-cpu-hog.yaml
- charts/kubernetes-chaos/templates/node-drain.yaml
- charts/kubernetes-chaos/templates/node-memory-hog.yaml
- charts/kubernetes-chaos/templates/node-taint.yaml
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-delete.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-network-corruption.yaml
- charts/kubernetes-chaos/templates/pod-network-duplication.yaml
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/templates/pod-network-loss.yaml
- charts/kubernetes-chaos/templates/serviceaccount.yaml
- charts/kubernetes-chaos/values.yaml
- move kubernetes-chaos chart from separate repo to this one. It's easier to get litmus up-and-running
- fixes #1736 (https://github.com/litmuschaos/litmus/issues/1736)
next steps:
- check code styles in kubernetes-chaos chart (should we rename that to something like: experiments, chaos) @ksatchit 
- update the main README
> Copy kubernetes-chaos to litmus-helm repo

- charts/kubernetes-chaos/templates/pod-delete.yaml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
-  Minor fix in pod delete chart
- fixes #
> fix(bug): Minor fix in pod delete chart

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/crds/chaosexperiment_crd.yaml
- charts/kubernetes-chaos/templates/clusterrole.yaml
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/disk-fill.yaml
- charts/kubernetes-chaos/templates/node-cpu-hog.yaml
- charts/kubernetes-chaos/templates/node-drain.yaml
- charts/kubernetes-chaos/templates/node-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-delete.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-network-corruption.yaml
- charts/kubernetes-chaos/templates/pod-network-duplication.yaml
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/templates/pod-network-loss.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/crds/chaosexperiment_crd.yaml
- charts/litmus/values.yaml
> update(helm): updating all the generic experiment cr

- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus/README.md
> update(readme): removing extra var from the README

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/values.yaml
> update(helm): update litmus helm chart for 1.7.0

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/clusterrole.yaml
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/disk-fill.yaml
- charts/kubernetes-chaos/templates/kubelet-service-kill.yaml
- charts/kubernetes-chaos/templates/node-drain.yaml
- charts/kubernetes-chaos/templates/node-io-stress.yaml
- charts/kubernetes-chaos/templates/node-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-delete.yaml
- charts/kubernetes-chaos/templates/pod-io-stress.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-network-corruption.yaml
- charts/kubernetes-chaos/templates/pod-network-duplication.yaml
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/templates/pod-network-loss.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
- Updates the litmus helm chart for 1.8.0 
- fixes #
> (chore)chart: update chart for 1.8.0 release

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/pod-network-corruption.yaml
- charts/kubernetes-chaos/templates/pod-network-duplication.yaml
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/templates/pod-network-loss.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/values.yaml
> chore(socketPath): correcting the socketPath env name

- README.md
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/values.yaml
> (chore)charts: update charts to appversion 1.8.2

- helmfile.yaml
- Adds helmfile for litmus 
- fixes #52 
> (feature)helmfile: add helmfile for litmus charts

- README.md
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/disk-fill.yaml
- charts/kubernetes-chaos/templates/disk-loss.yaml
- charts/kubernetes-chaos/templates/docker-service-kill.yaml
- charts/kubernetes-chaos/templates/kubelet-service-kill.yaml
- charts/kubernetes-chaos/templates/node-cpu-hog.yaml
- charts/kubernetes-chaos/templates/node-drain.yaml
- charts/kubernetes-chaos/templates/node-io-stress.yaml
- charts/kubernetes-chaos/templates/node-memory-hog.yaml
- charts/kubernetes-chaos/templates/node-taint.yaml
- charts/kubernetes-chaos/templates/pod-autoscaler.yaml
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-delete.yaml
- charts/kubernetes-chaos/templates/pod-io-stress.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-network-corruption.yaml
- charts/kubernetes-chaos/templates/pod-network-duplication.yaml
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/templates/pod-network-loss.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/clusterrole.yaml
- charts/litmus/templates/namespaced-role.yaml
- charts/litmus/values.yaml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
- This PR is for adding the flag with the experiment binary. This is according to the latest change in the experiment CR now the `./experiment` contains all experiments in this binary So to run the selective experiment we need to pass a flag accordingly. 
- fixes #
> chore(1.9.0): Update litmus helm to 1.9.0 

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/kubelet-service-kill.yaml
- charts/kubernetes-chaos/templates/node-cpu-hog.yaml
- charts/kubernetes-chaos/templates/node-drain.yaml
- charts/kubernetes-chaos/templates/node-io-stress.yaml
- charts/kubernetes-chaos/templates/node-memory-hog.yaml
- charts/kubernetes-chaos/templates/node-taint.yaml
- charts/kubernetes-chaos/templates/pod-io-stress.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> chore(v1.9.1): update all the charts version to 1.9.1

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/disk-fill.yaml
- charts/kubernetes-chaos/templates/node-cpu-hog.yaml
- charts/kubernetes-chaos/templates/node-io-stress.yaml
- charts/kubernetes-chaos/templates/node-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-delete.yaml
- charts/kubernetes-chaos/templates/pod-io-stress.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog.yaml
- charts/kubernetes-chaos/templates/pod-network-corruption.yaml
- charts/kubernetes-chaos/templates/pod-network-duplication.yaml
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/templates/pod-network-loss.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus-portal/Chart.yaml
- charts/litmus-portal/crds/chaosengine.yaml
- charts/litmus-portal/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/templates/clusterrole.yaml
- charts/litmus/templates/namespaced-role.yaml
- charts/litmus/values.yaml
> chore(helm): update charts to 1.10.0

- .github/workflows/guide.md
- .github/workflows/main.yml
Signed-off-by: Udit Gaurav <udit.gaurav@mayadata.io>
- This PR is for adding on-demand e2e run by commenting on a PR which will install litmus along with experiments from the latest commit on the PR which helps to catch any error in the PR.
- fixes #
> chore(helm): Add on demand e2e run on PR using github actions

- helmfile.yaml
- fixes #
- Adds Litmus portal to the helmfile
> (chore)helmfile: add litmus portal release into helmfile

- charts/litmus-portal/Chart.yaml
- charts/litmus-portal/values.yaml
Signed-off-by: Raj Babu Das <raj.das@mayadata.io>
- fixes #
> Change Litmus Portal frontend port change

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/disk-fill.yaml
- charts/kubernetes-chaos/templates/pod-network-corruption.yaml
- charts/kubernetes-chaos/templates/pod-network-duplication.yaml
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/templates/pod-network-loss.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus-portal/Chart.yaml
- charts/litmus-portal/crds/chaosengine.yaml
- charts/litmus-portal/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/values.yaml
> chore(1.11.0): updating helm templates

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-io-stress.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog.yaml
- charts/kubernetes-chaos/values.yaml
> (chore)charts: update kubernetes-chaos chart to 1.11.1

- charts/litmus/Chart.yaml
- charts/litmus/values.yaml
> (chore)chaos-runner: update chaos-runner to patch version 1.11.1

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/values.yaml
Signed-off-by: udit <udit.gaurav@mayadata.io>
- fixes #
> Chore(1.11.2): Updating helm template to 1.11.2

- .circleci/config.yml
Signed-off-by: udit <udit.gaurav@mayadata.io>
- fixes #
> Chore(fix): Fix helm lint in circle ci

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/clusterrole.yaml
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-io-stress.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus-portal/Chart.yaml
- charts/litmus-portal/crds/chaosengine.yaml
- charts/litmus-portal/templates/litmus-server-cluster-role-binding.yaml
- charts/litmus-portal/templates/litmus-server-cluster-role.yaml
- charts/litmus-portal/templates/litmus-server-role.yaml
- charts/litmus-portal/templates/litmus-server-rolebinding.yaml
- charts/litmus-portal/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/templates/clusterrole.yaml
- charts/litmus/templates/clusterrolebinding.yaml
- charts/litmus/templates/namespaced-role.yaml
- charts/litmus/templates/namespaced-rolebinding.yaml
- charts/litmus/values.yaml
> update(helm): updating helm charts to 1.12.0

- .circleci/config.yml
> (chore)build: move build env to ubuntu to run bash scripts

- .circleci/config.yml
> (chore)build: add packages to new build env

- .circleci/config.yml
- charts/litmus/Chart.yaml
- charts/litmus/templates/exporter-deployment.yaml
- charts/litmus/values.yaml
> (chore)chart: update chart litmus to 1.12.1

- .circleci/config.yml
> (chore)build: fix circle ci build for helm-3 charts

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/container-kill.yaml
- charts/kubernetes-chaos/templates/node-memory-hog.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus-portal/Chart.yaml
- charts/litmus-portal/crds/chaosengine.yaml
- charts/litmus-portal/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/values.yaml
> feat(v1.13.0): Updating helm template for 1.13.0

- charts/litmus/Chart.yaml
- charts/litmus/crds/chaosengine_crd.yaml
Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
- Removing maxProperties field from openapi validator for chaosengine CRD
- fixes #
> fix(crds): Removing maxProperties field from openapi validator for chaosengine

- README.md
- charts/litmus/Chart.yaml
- charts/litmus/crds/chaosengine_crd.yaml
- charts/litmus/crds/chaosexperiment_crd.yaml
- charts/litmus/crds/chaosresult_crd.yaml
- This PR is for updating the crd version to `v1` from `v1beta1`. 
- fixes #
> Chore(crds): Update CRD version to v1 from v1beta1

- charts/litmus-portal/Chart.yaml
- charts/litmus-portal/templates/frontend-ingress.yaml
- charts/litmus-portal/values.yaml
Adding chaos exporter environment variable
- fixes #
> Adding chaos exporter environment variable and fixing ingress

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/values.yaml
Upgrading Litmusportal to beta2
- fixes #
> Upgrading litmusportal to beta2

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/server-deployment.yaml
- charts/litmus-2-0-0-beta/values.yaml
> Adding svc name env

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/crds/chaosengine_crd.yaml
> (fix)crds: update chaosengine schema validation for annotation injection

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/values.yaml
> (chore)values: update portal components to 2.0.0Beta4

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/NOTES.txt
Signed-off-by: ishangupta-ds <ishan@chaosnative.com>
* 2.0 Beta Docs link were outdated for portal usage.
cc: @ksatchit @Jasstkn @ispeakc0de @rajdas98
> Litmus 2.0 beta docs link fix and charts version bumped.

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/ingress.yaml
> fixing ingress name in helm charts

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/ingress.yaml
Signed-off-by: Ramiro Berrelleza <rberrelleza@gmail.com>
Pass the value of the host to the ingress
- fixes #
> Use the right value for the host

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/server-role.yaml
Signed-off-by: ishangupta-ds <ishan@chaosnative.com>
Fixes for namespace scope of portal 
(elevating permissions for portal server to enable successful self agent creation)
@ksatchit @rajdas98 @Jonsy13 PTAL
> Fixes for ns scope (elevating permissions for portal server)

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/values.yaml
Replacing all non litmuschaos image repo to litmuschaos
- fixes #
> Replacing all non litmuschaos image repo to litmuschaos

- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/_helpers.tpl
- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/_helpers.tpl
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/_helpers.tpl
- fixes #
Incorrect indentation for custom labels :
```yaml
customLabels:
foo: bar
```
```yaml
apiVersion: litmuschaos.io/v1alpha1               
description:                                 
message: |                             
Scale the application replicas and test the node autoscaling on cluster
kind: ChaosExperiment                                                                                                                                                                                               
metadata: …
```
> FIX Custom labels indentation

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/values.yaml
> Upgrading to Litmus-2.0.0-Beta7

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/server-deployment.yaml
> Fix: Fix the env parsing in litmus portal

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/server-cluster-role.yaml
- charts/litmus-2-0-0-beta/values.yaml
> Removing privileged permissions from the rbac of litmus control plane and agent plane

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- This PR updates litmus-go to 1.13.7
- fixes #
> Chore(1.13.7): Update litmus-go to 1.13.7

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/pod-cpu-hog-exec.yaml
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog-exec.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/clusterrole.yaml
- charts/litmus/values.yaml
- Update charts templates for 1.13.8
- fixes #
> Chore(1.13.8): Update charts templates for 1.13.8

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/server-cluster-role.yaml
- charts/litmus-2-0-0-beta/templates/server-role.yaml
> chore(Litmus-Portal): Added RBAC fix for Ingress 

- charts/litmus-2-0-0-beta/Chart.yaml
- charts/litmus-2-0-0-beta/README.md
- charts/litmus-2-0-0-beta/templates/ingress.yaml
Hello everyone,
Iam sorry, my last pull request introduced a syntax error into ingress on reverting an edit : (.*)) 
Apologies.
Rémi
- fixes #
- [ X] DCO signed
- [X ] Chart Version bumped
> Fix Syntax Error into ingress path

- README-1-x.md
- README.md
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
- fixes #
> updating helm charts docs for 2.0.0

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
- charts/kubernetes-chaos/templates/pod-memory-hog-exec.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus-1-x/Chart.yaml
- charts/litmus-1-x/README.md
- charts/litmus-1-x/values.yaml
- Update experiment version to 2.0.0 from 1.13.8
- fixes #
> Chore(version-update): update chart version to 2.0.0 for litmus component

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/pod-network-partition.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus-1-x/Chart.yaml
- charts/litmus-1-x/README.md
- charts/litmus-1-x/crds/chaosengine_crd.yaml
- charts/litmus-1-x/templates/deployment.yaml
- charts/litmus-1-x/templates/exporter-deployment.yaml
- charts/litmus-1-x/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- This PR is for updating the chart version from 2.0.0 to 2.1.0.
- fixes #
> Release(2.1.0): Update the experiment manifest to 2.1.0

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/server-deployment.yaml
- charts/litmus/values.yaml
**This PR will** 
**-  Update the ChaosCenter to v2.3.0**
**-  Update the Litmus core to v2.2.0**
**-  Update the ChaosCharts branch to v2.2.x**
**-  Add an initContainer to server deployment for version upgrade of control-plane.**
- fixes #
> Update helmchart for ChaosCenter to v2.3.0

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-1-x/Chart.yaml
- charts/litmus-1-x/README.md
- charts/litmus-1-x/values.yaml
> Chore(2.3.0): update manifest to version to 2.3.0

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- This Pr is to fix the chart version of kube aws charts
- fixes #
> (Fix): Update the chart version for kube-aws charts

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/controlplane-configs.yaml
- charts/litmus/templates/server-cluster-role.yaml
- charts/litmus/templates/server-deployment.yaml
- charts/litmus/templates/server-svc.yaml
- charts/litmus/values.yaml
**This PR will upgrade the ChaosCenter helmChart to v2.4.0**
> **Note: This PR will be merged after v2.4.0 is released** 
- fixes #
> Upgrading ChaosCenter HelmChart to v2.4.0

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/server-deployment.yaml
- charts/litmus/values.yaml
**This PR add minikube option for custom grpc svc endpoint**
- fixes #
> Added minikube option for custom grpc svc endpoint

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/post-upgrade-hook.yaml
- charts/litmus/values.yaml
**This PR will add restartPolicy in upgrade agent**
- fixes #
> Added restartPolicy in upgrade agent

- .circleci/config.yml
Update current versions to the latest patch and add 1.23 minor release.
- fixes #
> fix(circleci): update k8s versions

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/templates/pod-network-latency.yaml
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> Update helm-charts for litmus 2.5.0

- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Update GCP & AZURE helmcharts to latest version & use latest tag for upgrade-agent

- .circleci/config.yml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
**This PR will** 
- upgrade litmus helm-chart to `2.6.0`.
- add version tag `v1.5.0` for helm-docs instead of `latest` 
- fixes #
> Update Litmus Helm-charts for 2.6.0

- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
Signed-off-by: Adarshkumar14 
- fixes #
> Adding resources limits and requests in values.yaml file

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/frontend-deployment.yaml
- charts/litmus/templates/mongo-sts.yaml
- charts/litmus/values.yaml
**This PR will disable auto mounting of default SA token for Frontend & MongoDB**
- fixes #
> Disabled auto mounting of default SA token for Frontend & MongoDB

- .circleci/config.yml
- fixes https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/
> [circle ci] update base image to the recommended

- . gitattributes
Better looking repository
- fixes #
> docs: add gitattributes to show YAML instead of mustache language

- .circleci/config.yml
- Update kind to 0.13.0 version
- Update images to the latest patch version
- Add test for running litmus on 1.24.0 Kubernetes version
- fixes #
> feat(tests): Add support for 1.24.0 Kubernetes in KIND

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/server-deployment.yaml
- charts/litmus/values.yaml
> Upgrade ChaosCenter from 2.9.0 to 2.10.0

- .github/CODEOWNERS
- charts/litmus/Chart.yaml
- charts/litmus/README.md
> Update imrajdas username in codeowners & chart info

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/_helpers.tpl
- charts/litmus/templates/auth-server-deployment.yaml
- charts/litmus/templates/controlplane-secrets.yaml
- charts/litmus/templates/mongo-sts.yaml
- charts/litmus/templates/post-upgrade-hook.yaml
- charts/litmus/templates/server-deployment.yaml
- charts/litmus/values.yaml
* add helper methods to create secret
* add helper method to get secre name
* update refs for secret to use helper method
Signed-off-by: Joseph Vano <joseph.vano@gmail.com>
- fixes #
> feat: add existingSecret value to override secret with ext secrets

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
Signed-off-by: Adarshkumar14 <adarsh.kumar@harness.io>
- fixes #
> Updating the helm chart with the 2.11.0 release

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
Signed-off-by: uditgaurav <udit@chaosnative.com>
- This PR will update the litmus experiment version to 2.11.0
- fixes #
> Chore(2.11.0): Update Experiment Charts for 2.11.0

- .circleci/config.yml
- fixes #
Example of broken tests(mistake in the service name): https://github.com/litmuschaos/litmus-helm/pull/258/commits/1dba3f7f9735267159eca3f4d3f246e6efb5b1c1
Last commit fixes it. 
> ci: Add frontend's probe to verify chart

- .circleci/config.yml
> Bump kind to 0.14.0

- .circleci/config.yml
> better: stale helm-docs output

- .circleci/config.yml
> remove support for 1.16 k8s and fix typo

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/server-cluster-role.yaml
- charts/litmus/templates/server-deployment.yaml
- charts/litmus/templates/server-role.yaml
- charts/litmus/values.yaml
Signed-off-by: Vedant <vedant.srotria@harness.io>
- fixes #
> Upgraded litmus charts to 2.12.0 ChaosCenter

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/frontend-deployment.yaml
- charts/litmus/values.yaml
Signed-off-by: Vedant <vedant.srotria@harness.io>
- fixes #
> Added upgrade changes for 2.13.0 chaoscenter release

- CONTRIBUTING.md
- upgrades contributing guide to make it clear the versioning policy for litmus charts.
- fixes #
> Upgrade contributing guide

- .circleci/config.yml
- bump kind to `0.16.0`
- update k8s images to latest patches
- add k8s `1.25.2`
- fixes #
> Bump kind to 0.16.0 & k8s versions

- README.md
Signed-off-by: ksatchit <karthik.s@harness.io>
- fixes #
> (chore)(readme) add admin credentials info into readme

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/templates/server-cluster-role.yaml
- charts/litmus/templates/server-role.yaml
- charts/litmus/values.yaml
Signed-off-by: Akash Shrivastava <akash.shrivastava@harness.io>
- fixes #
> Added upgrade changes for 2.14.0 chaoscenter release 

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/templates/azure-instance-stop.yaml
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/templates/gcp-vm-disk-loss.yaml
- charts/kube-gcp/templates/gcp-vm-instance-stop.yaml
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/crds/chaosengine_crd.yaml
- charts/litmus-core/values.yaml
- Update core component manifest for 2.14.0
- fixes #
> Release(2.14.0): Update core component manifest for 2.14.0

- README.md
- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/templates/crds.yaml
Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>
- fixes #
> chore(agent-helm): updating agent-helm for 3.0.0-beta3 version

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/templates/hook-pre-install-job.yaml
Signed-off-by: Shubham Chaudhary <shubham.chaudhary@harness.io>
- fixes #
> chore(hub): updating the hub branch name

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/README.md.gotmpl
- charts/litmus/templates/ingress.yaml
- charts/litmus/values.yaml
> feat: allow to specify pathType via values

- .github/workflows/release.yml
> Add mongodb repo to release

- .github/workflows/test.yml
> Exclude kubernetes-chaos,kube-aws,kube-azure,kube-gcp,litmus-agent from install

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/templates/hook-pre-install-job.yaml
- charts/litmus-agent/values.yaml
> Added changes for making litmus-agent compatible with 3.0.0-beta7 ChaosCenter

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/templates/hook-pre-install-job.yaml
> Upgrading litmus-agent for compatibility with ChaosCenter 3.0.0-beta8

- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
release litmus 3.5.0 as a chart
- fixes #
> release litmus 3.5.0

- README.md
- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/values.yaml
**This PR will upgrade litmus-helm-agent to 3.5.x**
**Command for Installing Agent -** 
```
helm install litmus-agent ./charts/litmus-agent -n litmus \
--set "INFRA_NAME=helm-agent-1" \
--set "LITMUS_URL=http://chaos-litmus-frontend-service:9091" \
--set "LITMUS_USERNAME=****" \
--set "LITMUS_PASSWORD=****" \
--set "LITMUS_PROJECT_ID=87392669-1e94-487e-b0b7-dccefea2bd12" \
--set "LITMUS_ENVIRONMENT_ID=testenv" \
--set "crds.create=false" \
--set "workflow-controller.crds.create=false" \
--set "global.INFRA_MODE=namespace"
```
**Output for same -** 
```
NAME: litmus-agent
LAST DEPLOYED: Fri Apr  5 18:25:26 2024
NAMESPACE: litmus
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
**Pods of all components deployed -**
```
litmus        litmus-agent-event-tracker-bd5c9979d-ddwt9          1/1 …
```
> Added changes for upgrading litmus-helm-agent to 3.5.x

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/templates/crds.yaml
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Added changes for upgrading litmus-helm-agent to 3.6.x and release 3.6.0

- .github/CODEOWNERS
- fixes https://github.com/litmuschaos/litmus-helm/issues/279
> Update CODEOWNERS for litmus-helm

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.7.0): Updating the core helm-charts for 3.7.0

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Added 3.8.x Helm Chart for ChaosCenter & Litmus-Agent

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.8.0): Updating the core helm-charts for 3.8.0

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
> Fixed chart.yaml in Litmus-Helm-Agent Helm

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.9.0): Updating the core helm-charts for 3.9.0

- .github/workflows/release.yml
- fixes #399 
cc. @Jonsy13 @namkyu1999 
> Push to ghcr only when the chart has changes

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.11.0): Add the helm charts for 3.11.0 version

- README.md
- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/templates/secret.yaml
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Added 3.11.x changes for ChaosCenter & Helm-Agent

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.13.0): Add the helm charts for 3.13.0 version

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Added chart changes for 3.13.x Litmus Helm/Agent

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-exporter/templates/_helpers.tpl
- charts/litmus-agent/charts/chaos-exporter/templates/deployment.yaml
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/chaos-operator/templates/_helpers.tpl
- charts/litmus-agent/charts/chaos-operator/templates/deployment.yaml
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/event-tracker/templates/_helpers.tpl
- charts/litmus-agent/charts/event-tracker/templates/deployment.yaml
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/charts/subscriber/templates/_helpers.tpl
- charts/litmus-agent/charts/subscriber/templates/deployment.yaml
- charts/litmus-agent/charts/workflow-controller/Chart.yaml
- charts/litmus-agent/charts/workflow-controller/README.md
- charts/litmus-agent/charts/workflow-controller/templates/_helpers.tpl
- charts/litmus-agent/charts/workflow-controller/templates/deployment.yaml
- charts/litmus-agent/templates/_helpers.tpl
- charts/litmus-agent/templates/hook-pre-install-job.yaml
- charts/litmus-agent/values.yaml
Update the litmus-agent charts to fix the global.podAnnotations value also added the podannotations to the job agent.
- fixes #404
> Fix agent global pod annotations

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.14.0): Add the helm charts for 3.14.0 version

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.15.0): Add the helm charts for 3.15.0 version

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Added changes for 3.15.x - Helm-Agent & ChaosCenter

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Added changes for 3.16.x

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.16.0): Adding the helm charts for 3.16.0 version

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.17.0): Adding the helm charts for 3.17.0 version

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.18.0): Adding the helm charts for 3.18.0 version

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Updated helm version to 3.18.x for Litmus & Helm Agent

- charts/kube-aws/Chart.yaml
- charts/kube-aws/README.md
- charts/kube-aws/values.yaml
- charts/kube-azure/Chart.yaml
- charts/kube-azure/README.md
- charts/kube-azure/values.yaml
- charts/kube-gcp/Chart.yaml
- charts/kube-gcp/README.md
- charts/kube-gcp/values.yaml
- charts/kubernetes-chaos/Chart.yaml
- charts/kubernetes-chaos/README.md
- charts/kubernetes-chaos/values.yaml
- charts/litmus-core/Chart.yaml
- charts/litmus-core/README.md
- charts/litmus-core/values.yaml
> chore(3.19.0): Adding the helm charts for 3.19.0 version

- charts/litmus-agent/Chart.yaml
- charts/litmus-agent/README.md
- charts/litmus-agent/charts/chaos-exporter/Chart.yaml
- charts/litmus-agent/charts/chaos-exporter/README.md
- charts/litmus-agent/charts/chaos-operator/Chart.yaml
- charts/litmus-agent/charts/chaos-operator/README.md
- charts/litmus-agent/charts/event-tracker/Chart.yaml
- charts/litmus-agent/charts/event-tracker/README.md
- charts/litmus-agent/charts/subscriber/Chart.yaml
- charts/litmus-agent/charts/subscriber/README.md
- charts/litmus-agent/values.yaml
- charts/litmus/Chart.yaml
- charts/litmus/README.md
- charts/litmus/values.yaml
> Added changes for helm-litmus-3.19.x
