charts/litmus/Chart.yaml
charts/litmus/templates/deployment.yaml
charts/litmus/values.yaml

- Updates deploy specs and adds runner, exporter specs to values.yaml
- Updates image and chart versions to 1.2.2

(chore)chart_versions: update litmus helm chart to 1.2.2 release

---

charts/litmus/templates/deployment.yaml

- This PR removes the `chart` label from selectors in the operator deployment template. Keeping the chart label in the selector list will cause a failure during helm upgrades (where the chart version change will result in essentially a different label value, in turn causing patch failures) -- the selectors are supposed to be immutable.
- Also updates the label keys to be shorter and simpler.

(fix)charts: remove chart labels from selector list

---

.github/PULL_REQUEST_TEMPLATE.md
charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/deployment.yaml
charts/litmus/values.yaml

Add support for disabling google analytics in chaos operator, because it could be a security issue for using litmus.
- fixes #18

Add opportunity to enable or disable google analytics in chaos operator

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/values.yaml

- update docker tag of chaos-operator & chaos-runner to 1.5.1

Update chart with 1.5.1 version of litmus

---

charts/litmus/Chart.yaml
charts/litmus/templates/clusterrole.yaml
charts/litmus/templates/namespaced-role.yaml

- Fixes an error in operator metrics initialization caused due to lack of permissions on replicasets
- Adds openshift resources to the role/clusterrole of operator making it consistent with the [standard manifests](https://github.com/litmuschaos/litmus/blob/master/docs/litmus-operator-v1.6.2.yaml#L22)
- fixes #40 

(fix)role: add replicaset permissions for operator

---

charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/README.md
charts/kubernetes-chaos/templates/clusterrole.yaml
charts/kubernetes-chaos/templates/clusterrolebinding.yaml
charts/kubernetes-chaos/templates/container-kill.yaml
charts/kubernetes-chaos/templates/disk-fill.yaml
charts/kubernetes-chaos/templates/disk-loss.yaml
charts/kubernetes-chaos/templates/docker-service-kill.yaml
charts/kubernetes-chaos/templates/kubelet-service-kill.yaml
charts/kubernetes-chaos/templates/node-cpu-hog.yaml
charts/kubernetes-chaos/templates/node-drain.yaml
charts/kubernetes-chaos/templates/node-memory-hog.yaml
charts/kubernetes-chaos/templates/pod-autoscaler.yaml
charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
charts/kubernetes-chaos/templates/pod-delete.yaml
charts/kubernetes-chaos/templates/pod-memory-hog.yaml
charts/kubernetes-chaos/templates/pod-network-corruption.yaml
charts/kubernetes-chaos/templates/pod-network-duplication.yaml
charts/kubernetes-chaos/templates/pod-network-latency.yaml
charts/kubernetes-chaos/templates/pod-network-loss.yaml
charts/kubernetes-chaos/templates/serviceaccount.yaml
charts/kubernetes-chaos/values.yaml

- Update (generic) kubernetes-chaos charts to 1.7.0
- fixes #

(chore)charts: update kubernetes (generic) chaos chart to 1.7.0

---

charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/templates/container-kill.yaml
charts/kubernetes-chaos/templates/disk-fill.yaml
charts/kubernetes-chaos/templates/disk-loss.yaml
charts/kubernetes-chaos/templates/docker-service-kill.yaml
charts/kubernetes-chaos/templates/kubelet-service-kill.yaml
charts/kubernetes-chaos/templates/node-cpu-hog.yaml
charts/kubernetes-chaos/templates/node-drain.yaml
charts/kubernetes-chaos/templates/node-memory-hog.yaml
charts/kubernetes-chaos/templates/node-taint.yaml
charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
charts/kubernetes-chaos/templates/pod-delete.yaml
charts/kubernetes-chaos/templates/pod-memory-hog.yaml
charts/kubernetes-chaos/templates/pod-network-corruption.yaml
charts/kubernetes-chaos/templates/pod-network-duplication.yaml
charts/kubernetes-chaos/templates/pod-network-latency.yaml
charts/kubernetes-chaos/templates/pod-network-loss.yaml

Not sure if this was a bug but it solved it for me:
The `ChaosResults` name is always different to what the Chaos Runner expects:
ChaosEngine name: `api-gateway-1-200904`
ChaosExperiment name: `k8s-pod-network-loss` <--- from helm chart
ChaosResult name: `api-gateway-1-200904-pod-network-loss` <--- auto created? missing the k8s prefix
Chaos Runner error:
```
I0904 04:01:03.070760       1 runner.go:76] Unable to Update ChaosEngine Status due to: Unable to get ChaosResult Name: api-gateway-1-200904-k8s-pod-network-loss in namespace: litmus, due to error: chaosresults.litmuschaos.io "api-gateway-1-200904-k8s-pod-network-loss" not found: chaosresults.litmuschaos.io "api-gateway-1-200904-k8s-pod-network-loss" not found
```
I've tried updating the `Spec.Definitions.Labels.Name` field from …

remote prefix from ChaosExperiments

---

charts/litmus-portal/Chart.yaml
charts/litmus-portal/templates/mongo-pvc.yaml
charts/litmus-portal/templates/portal-frontend-svc.yaml
charts/litmus-portal/values.yaml

- Make the pvc size, storageClass, and accessMode properties for Mongo configurable
- Allow specification of frontend-service NodePort 

[litmus-portal] Option to override Mongo pvc & frontend-service NodePort values

---

.circleci/config.yml
.github/CODEOWNERS
README.md
charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/README.md
charts/litmus-2-0-0-beta/Chart.yaml
charts/litmus-2-0-0-beta/README.md
charts/litmus/Chart.yaml
charts/litmus/README.md

- Added deploy for charts under charts/ folder
- CODEOWNERS is more specific based on the maintainers of each chart
- Test compatibility with different kubernetes versions
- Added deployment verification for litmus* charts:
```
kubectl wait --for=condition=Ready pod --all -n chaos --timeout=300s
```
- partially fixes #27 

Add deploy tests

---

charts/litmus-2-0-0-beta/Chart.yaml
charts/litmus-2-0-0-beta/README.md

Fixes error:
```
Error: Failed to render chart: exit status 1: Error: chart requires kubeVersion: >=1.16 which is incompatible with Kubernetes v1.19.8-gke.1600
```
This issue is possibly reproducing in the other Clouds which have following Kubernetes version format: 1.20.2-xx
Example of fix: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml#L23

Fix incompatibility when install to GKE

---

charts/litmus-2-0-0-beta/Chart.yaml
charts/litmus-2-0-0-beta/README.md
charts/litmus-2-0-0-beta/values.yaml

Signed-off-by: ishangupta-ds <ishan@chaosnative.com>
* This PR adds environment variables for litmus 2.0 server
- `PORTAL_ENDPOINT` for the graphql server endpoint to be used in namespaced mode of portal installation.
> Defaults to `http://litmusportal-server-service:9002`
- `CONTAINER_RUNTIME_EXECUTOR` for tuning argo workflow controller's CNE
> Defaults to `k8sapi`
@ksatchit @rajdas98 @ispeakc0de @Jasstkn

Adding envs for ns scope and argo's container runtime executor.

---

charts/litmus-2-0-0-beta/Chart.yaml
charts/litmus-2-0-0-beta/README.md
charts/litmus-2-0-0-beta/values.yaml

Signed-off-by: ishangupta-ds <ishan@chaosnative.com>
* This PR adds environment variable for litmus 2.0 server
- `HUB_BRANCH_NAME` for the graphql server to be used for ChaosHubs feature.
> Defaults to `v1.13.x`
@ksatchit @rajdas98 @ispeakc0de @Jasstkn

Adding HUB_BRANCH_NAME env. for server

---

charts/litmus-2-0-0-beta/Chart.yaml
charts/litmus-2-0-0-beta/README.md
charts/litmus-2-0-0-beta/templates/server-deployment.yaml

PORTAL_ENDPOINT variable is required when Litmus Portal runs in namespaced mode. 
This is used to construct the GraphQL URL: https://github.com/litmuschaos/litmus/blob/c947580814668a8c85cf817e56ef08b2c8192764/litmus-portal/graphql-server/pkg/file_handlers/file_handlers.go#L66
Signed-off-by: Radu Domnu <radu.domnu@gmail.com>
- fixes #

Added PORTAL_ENDPOINT variable when portal runs namespaced mode

---

charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/README.md
charts/kubernetes-chaos/crds/chaosexperiment_crd.yaml
charts/kubernetes-chaos/templates/disk-fill.yaml
charts/kubernetes-chaos/templates/kubelet-service-kill.yaml
charts/kubernetes-chaos/templates/node-cpu-hog.yaml
charts/kubernetes-chaos/templates/node-drain.yaml
charts/kubernetes-chaos/templates/node-io-stress.yaml
charts/kubernetes-chaos/templates/node-memory-hog.yaml
charts/kubernetes-chaos/templates/node-taint.yaml
charts/kubernetes-chaos/templates/pod-dns-error.yaml
charts/kubernetes-chaos/templates/pod-dns-spoof.yaml
charts/kubernetes-chaos/values.yaml
charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/crds/chaosengine_crd.yaml
charts/litmus/crds/chaosexperiment_crd.yaml
charts/litmus/values.yaml

Signed-off-by: shubhamchaudhary <shubham@chaosnative.com>
- updating charts for the litmus 1.13.5 version
- adding pod-dns-spoof and pod-dns-error experiments
- updating crds for the latest changes
- fixes #

helm(1.13.5): updating charts for 1.13.5

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/exporter-svc.yaml

This PR fixes helm installation when exporter.enabled is set to true
It presently fails as the labels and selectors on exporter-svc.yaml are incorrectly indented 

Fix indentation of selectors and labels on exporter-svc.yaml

---

charts/litmus-2-0-0-beta/Chart.yaml
charts/litmus-2-0-0-beta/README.md
charts/litmus-2-0-0-beta/templates/mongo-sts.yaml
charts/litmus-2-0-0-beta/values.yaml

This adds a simple option that allows users to set the service account
used by mongo. This service account must be created by the user. If this
field is omitted, no service account is configured for mongo.
Signed-off-by: Nikolas Skoufis <nskoufis@seek.com.au>
@rajdas98 @ispeakc0de @Jasstkn 
Adds an optional service account for the mongo statefulset pods, which enables users of PSPs to provide this pod with the correct permissions.
- fixes #136 

Add value for setting mongo service account

---

.circleci/config.yml

- Add 1.21.1 Kubernetes version to run tests against
- Bump to the latest version for 1.17-1.20 Kubernetes
- Bump kind itself to 0.11.1

Add 1.21.1 k8s cluster, update minor version and kind itself

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/ingress.yaml
charts/litmus/values.yaml

Signed-off-by: Rémi ZIOLKOWSKI <remi.ziolkowski-ext@pole-emploi.fr>
This permit the user to configure path for the ingress depending of ingress controller ( kubernetes-nginx, ingress-nginx, traefik, etc... )
We need it cause the helm chart is un-usable without it
- fixes #

Configure ingress paths from values.yaml

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/ingress.yaml

Signed-off-by: Tuan Anh Tran <me@tuananh.org>
the service is generated using `$fullname` but reference service name in ingress is hardcode.
Fix #174

fix(litmus): do not hardcode svc name in ingress

---

charts/kube-aws/Chart.yaml
charts/kube-aws/README.md
charts/kube-aws/values.yaml
charts/kube-azure/Chart.yaml
charts/kube-azure/README.md
charts/kube-azure/values.yaml
charts/kube-gcp/Chart.yaml
charts/kube-gcp/README.md
charts/kube-gcp/values.yaml
charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/README.md
charts/kubernetes-chaos/templates/pod-cpu-hog.yaml
charts/kubernetes-chaos/values.yaml
charts/litmus-core/Chart.yaml
charts/litmus-core/README.md
charts/litmus-core/values.yaml

- Update charts for 2.6.0
- Add CPU hog tunables
- Remove chaos kill command from pod-memory-hog as it is only required in pod-memory-hog-exec

Chore(2.6.0): Update backend charts for 2.6.0

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/ingress.yaml
charts/litmus/values.yaml

Signed-off-by: stoehdoi <domi.stoehr@googlemail.com>
Ingress class should be defined in the spec rather than in the annotations: https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource 
For some ingress controller implementations this could be a breaking change. For example, the admission controller of nginx IC does not allow specifying the ingress class in both directives, annotations and spec. Hence, making the `.spec.ingressClassName` conditional. 
cc: @rajdas98 @ispeakc0de @Jasstkn

support ingress class definition in spec

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/server-cluster-role.yaml
charts/litmus/templates/server-role.yaml

Signed-off-by: Raj Babu Das <mail.rajdas@gmail.com>
adding missing permission to subscriber and eventtracker role
- fixes #

adding missing permission to subscriber and eventtracker role

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/controlplane-configs.yaml
charts/litmus/templates/frontend-vs.yaml
charts/litmus/templates/ingress.yaml
charts/litmus/values.yaml

Signed-off-by: Vedant Shrotria <vedant.shrotria@harness.io>
**This PR will -** 
- Add support for prefix in virtual-service for istio
- Fixes the hardcoded name of frontend-service in virtual-service
- Fixes namespace in Ingress
- Adds Support for envoy proxy through frontend-nginx-config.
**Above changes have been tested with Ingress as well as Virtual service, both are working fine with `/` & `/litmuschaos` paths.** 
- fixes #

Updated helmchart for supporting prefixPath in virtual-service and envoy proxy(Istio)

---

charts/kube-aws/Chart.yaml
charts/kube-aws/README.md
charts/kube-aws/values.yaml
charts/kube-azure/Chart.yaml
charts/kube-azure/README.md
charts/kube-azure/values.yaml
charts/kube-gcp/Chart.yaml
charts/kube-gcp/README.md
charts/kube-gcp/values.yaml
charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/README.md
charts/kubernetes-chaos/values.yaml
charts/litmus-core/Chart.yaml
charts/litmus-core/README.md
charts/litmus-core/values.yaml

Signed-off-by: Akash Shrivastava <akash.shrivastava@harness.io>
This PR updates the Helm charts for the v2.10.0 release
`kubernetes-chaos/values.yaml` chart was not updated in the last release PR. Have bumped it to 2.10.0 from 2.8.0

Chore(2.9.0): Update helm docs for version 2.9.0 

---

charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/README.md
charts/kubernetes-chaos/templates/pod-http-latency.yaml
charts/kubernetes-chaos/templates/pod-http-modify-body.yaml
charts/kubernetes-chaos/templates/pod-http-modify-header.yaml
charts/kubernetes-chaos/templates/pod-http-reset-peer.yaml
charts/kubernetes-chaos/templates/pod-http-status-code.yaml

- This PR adds HTTP Chaos Experiment Charts to helm - This will allow to install the experiment CR using helm. The experiments are:
- pod-http-modify-body
- pod-http-modify-header
- pod-http-reset-peer
- pod-http-response-code
- pod-http-network-latency
- fixes #

Chore(http-chaos): Add Charts for the new http chaos experiments 

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/post-upgrade-hook.yaml
charts/litmus/values.yaml

Fix added upgradeAgent resources limits/requests to template
on our clusters we're forced to, (and it is considered as best-practice to), have resources limits/requests on all of our workloads. Not having them on upgrade agent makes it fail to start and therefore makes us impossible to upgrade litmus with this chart
Special notes for your reviewer:

Fix added upgradeAgent resources limits/requests to template

---

charts/litmus-core/Chart.yaml
charts/litmus-core/README.md
charts/litmus-core/templates/exporter-deployment.yaml
charts/litmus-core/values.yaml

This PR allows you to set custom annotations on the exporter deployment. This allows users to add custom Prometheus/DataDog annotations so the metrics can be scraped.

Allow custom annotations to be set on the exporter deployment

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/frontend-deployment.yaml

Wrong indentation results in:
```
W0123 11:36:05.715892   60004 warnings.go:70] unknown field "spec.strategy.maxSurge"
W0123 11:36:05.716037   60004 warnings.go:70] unknown field "spec.strategy.maxUnavailable"
W0123 11:36:05.716041   60004 warnings.go:70] unknown field "spec.type"
```

Fix frontend-deployment updateStrategy

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/auth-server-deployment.yaml
charts/litmus/templates/frontend-deployment.yaml

Sorry, should have used/tested locally instead of through Github UI - this fixes the indentation to `nindent` instead of `indent` which all other deployments are using.

Switch to nindent for frontend like others

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/post-upgrade-hook.yaml

This prevents the following errors:
```
Error: UPGRADE FAILED: post-upgrade hooks failed: warning: Hook post-upgrade litmus/templates/post-upgrade-hook.yaml failed: jobs.batch "chaos-litmus-upgrade-agent-cp" already exists
```
and will produce a new job on each upgrade.

Give the update hook a unique name.

---

.github/workflows/test.yml

Optimize chart exclusion in GA

---

charts/litmus-agent/Chart.yaml
charts/litmus-agent/README.md
charts/litmus-agent/charts/chaos-exporter/Chart.yaml
charts/litmus-agent/charts/chaos-exporter/README.md
charts/litmus-agent/charts/chaos-exporter/templates/_helpers.tpl
charts/litmus-agent/charts/chaos-exporter/templates/deployment.yaml
charts/litmus-agent/charts/chaos-exporter/values.yaml
charts/litmus-agent/charts/chaos-operator/Chart.yaml
charts/litmus-agent/charts/chaos-operator/README.md
charts/litmus-agent/charts/chaos-operator/templates/_helpers.tpl
charts/litmus-agent/charts/chaos-operator/templates/deployment.yaml
charts/litmus-agent/charts/chaos-operator/values.yaml
charts/litmus-agent/charts/event-tracker/Chart.yaml
charts/litmus-agent/charts/event-tracker/README.md
charts/litmus-agent/charts/event-tracker/templates/_helpers.tpl
charts/litmus-agent/charts/event-tracker/templates/deployment.yaml
charts/litmus-agent/charts/event-tracker/values.yaml
charts/litmus-agent/charts/subscriber/Chart.yaml
charts/litmus-agent/charts/subscriber/README.md
charts/litmus-agent/charts/subscriber/templates/_helpers.tpl
charts/litmus-agent/charts/subscriber/templates/deployment.yaml
charts/litmus-agent/charts/subscriber/values.yaml
charts/litmus-agent/charts/workflow-controller/Chart.yaml
charts/litmus-agent/charts/workflow-controller/README.md
charts/litmus-agent/charts/workflow-controller/templates/_helpers.tpl
charts/litmus-agent/charts/workflow-controller/templates/deployment.yaml
charts/litmus-agent/charts/workflow-controller/values.yaml
charts/litmus-agent/templates/_helpers.tpl
charts/litmus-agent/templates/hook-pre-install-job.yaml
charts/litmus-agent/values.yaml

Add custom label for resources in litmus-agent chart

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/auth-server-deployment.yaml
charts/litmus/templates/server-deployment.yaml
charts/litmus/values.yaml

- Add securityContext in values.yaml
- Using this securityContext in auth-server-deployment.yaml and server-deployment.yaml
- Bumping Chart version to 2.16.0 (I hesitate between bumping to 2.16.0 or 2.15.12 cause not sure if this change can be considered a bug fix)
- Regenerating docs with helm-docs
- fixes #331

Add security context for wait-for-mongodb

---

README.md
charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/_helpers.tpl
charts/litmus/templates/auth-server-deployment.yaml
charts/litmus/templates/controlplane-configs.yaml
charts/litmus/templates/frontend-deployment.yaml
charts/litmus/templates/server-deployment.yaml
charts/litmus/values-ci.yaml
charts/litmus/values.yaml

Added changes required in helm charts for Litmus 3.0.0

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/frontend-route.yaml
charts/litmus/values.yaml

- Add common and custom labels to the route resource
- Upgrade chart version to 2.15.12
- Regenerate doc with helm-docs
- fixes #336

Add labels in openshift route resource

---

README.md
charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/post-upgrade-hook.yaml
charts/litmus/values.yaml

It allows users of this helm chart to opt-out for the post upgrade hook.
- fixes 341

Post upgrade hook fix

---

charts/litmus-agent/Chart.yaml
charts/litmus-agent/README.md
charts/litmus-agent/templates/hook-pre-install-job.yaml
charts/litmus-agent/values.yaml

The version of the chaoscenter was hardcoded in the template of the litmus-agent charts that was posing problem when deploying with different version of chaoscenter. The version is now a variable.
- fixes #329 

Remove hardcoded version of chaoscenter in pre-hook job in litmus-agent chart #329

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/values.yaml

Added changes for supporting MongoDB on Mac M1

---

charts/litmus-agent/Chart.yaml
charts/litmus-agent/README.md
charts/litmus-agent/templates/infra-config-map-workflow.yaml
charts/litmus-agent/templates/infra-config-map.yaml
charts/litmus-agent/templates/infra-secret.yaml
charts/litmus-agent/templates/secret.yaml
charts/litmus-agent/values.yaml

When using the Litmus Agent chart, we can set `global.infraConfigName` and `global.infraSecretName` but we can't use an existing (already in cluster) config or secret.
- fixes #311
This is a rework of https://github.com/litmuschaos/litmus-helm/pull/313 with the addition of the ability to use an existing `ConfigMap`.

Litmus Agent: allow using existing configuration and secrets

---

.github/workflows/main.yml
.github/workflows/portal.yml

In workflow, `set-output` command is deprecated and will be disabled soon. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
https://github.com/litmuschaos/litmus-helm/blob/3f8e313097632f354ea2f14044cb6ac0ad8b9259/.github/workflows/main.yml#L32-L34
https://github.com/litmuschaos/litmus-helm/blob/3f8e313097632f354ea2f14044cb6ac0ad8b9259/.github/workflows/portal.yml#L32-L34
- fixes #392

Replace deprecated command with environment file

---

.github/workflows/release.yml

This PR implements the process to publish helm charts to the GitHub Container Registry (GHCR) within our existing release pipeline.
Closes #391 
cc. @Jonsy13 , @namkyu1999 

Publish helm charts to GitHub Container Registry

---

charts/kube-aws/Chart.yaml
charts/kube-aws/README.md
charts/kube-aws/values.yaml
charts/kube-azure/Chart.yaml
charts/kube-azure/README.md
charts/kube-azure/values.yaml
charts/kube-gcp/Chart.yaml
charts/kube-gcp/README.md
charts/kube-gcp/values.yaml
charts/kubernetes-chaos/Chart.yaml
charts/kubernetes-chaos/README.md
charts/kubernetes-chaos/values.yaml
charts/litmus-core/Chart.yaml
charts/litmus-core/README.md
charts/litmus-core/values.yaml

chore(3.12.0): Add the helm charts for 3.12.0 version

---

charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/templates/_helpers.tpl
charts/litmus/templates/auth-server-deployment.yaml
charts/litmus/templates/frontend-deployment.yaml
charts/litmus/templates/server-deployment.yaml
charts/litmus/values.yaml

- Add podAnnotations value to add podannotations on each components
- Add customPodAnnotation value to add podannotations on all components
- bumped version 3.11.1 and regenerated docs
- fixes #404 
This PR is inspired by https://github.com/litmuschaos/litmus-helm/pull/274/ but which is inactive for quite a long time. If needed, I can close this PR in favor of the old one if it become active again.

Add pod annotations support

---

charts/litmus-agent/Chart.yaml
charts/litmus-agent/README.md
charts/litmus-agent/charts/chaos-exporter/Chart.yaml
charts/litmus-agent/charts/chaos-exporter/README.md
charts/litmus-agent/charts/chaos-operator/Chart.yaml
charts/litmus-agent/charts/chaos-operator/README.md
charts/litmus-agent/charts/event-tracker/Chart.yaml
charts/litmus-agent/charts/event-tracker/README.md
charts/litmus-agent/charts/subscriber/Chart.yaml
charts/litmus-agent/charts/subscriber/README.md
charts/litmus-agent/values.yaml
charts/litmus/Chart.yaml
charts/litmus/README.md
charts/litmus/values.yaml

Added changes for 3.14.x
